// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace Timeinator.Mobile.DataAccess.Migrations
{
    [DbContext(typeof(TimeinatorMobileDbContext))]
    [Migration("20181128211351_TaskDatesAndSettingsType")]
    partial class TaskDatesAndSettingsType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Timeinator.Mobile.DataAccess.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Timeinator.Mobile.DataAccess.TimeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsImmortal");

                    b.Property<bool>("IsImportant");

                    b.Property<string>("Name");

                    b.Property<int>("Priority");

                    b.Property<float>("Progress");

                    b.Property<string>("Tag");

                    b.Property<DateTime>("TargetStartDate");

                    b.HasKey("Id");

                    b.ToTable("TimeTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
